<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Category;
use App\Models\Product;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        User::create([
            'name' => 'Administrator',
            'email' => 'admin@mitrast.com',
            'password' => Hash::make('admin123'),
        ]);

        $categories = [
            [
                'name' => 'Komponen Mesin Kapal',
                'slug' => 'komponen-mesin-kapal',
                'description' => 'Supplier komponen dan sparepart mesin kapal terlengkap untuk berbagai jenis mesin diesel marine, mulai dari piston ring, cylinder liner, turbocharger, hingga fuel injection pump. Produk original dengan kualitas terjamin.',
                'meta_title' => 'Jual Komponen Mesin Kapal - Sparepart Mesin Diesel Marine',
                'meta_description' => 'Supplier komponen dan suku cadang mesin kapal terlengkap: piston ring, cylinder liner, turbocharger, fuel injection pump, crankshaft bearing. Kualitas original untuk mesin diesel marine.',
                'sort_order' => 1,
            ],
            [
                'name' => 'Peralatan Navigasi',
                'slug' => 'peralatan-navigasi',
                'description' => 'Distributor peralatan navigasi kapal terlengkap termasuk kompas magnetik, GPS marine, radio VHF, radar, dan peralatan komunikasi kapal lainnya. Produk standar SOLAS dan IMO.',
                'meta_title' => 'Jual Peralatan Navigasi Kapal - GPS, Kompas, Radio VHF Marine',
                'meta_description' => 'Toko peralatan navigasi kapal terlengkap: kompas magnetik marine, GPS navigator, radio VHF DSC, radar, echo sounder. Standar SOLAS dan IMO, harga kompetitif.',
                'sort_order' => 2,
            ],
            [
                'name' => 'Peralatan Keselamatan',
                'slug' => 'peralatan-keselamatan',
                'description' => 'Supplier peralatan keselamatan kapal sesuai standar SOLAS dan IMO. Tersedia life jacket, life raft, fire extinguisher, EPIRB, SART, dan perlengkapan keselamatan kapal lainnya.',
                'meta_title' => 'Jual Peralatan Keselamatan Kapal - SOLAS Approved Equipment',
                'meta_description' => 'Supplier peralatan keselamatan kapal SOLAS approved: life jacket, life raft, fire extinguisher CO2, EPIRB 406MHz, SART, immersionsuit. Sertifikasi lengkap.',
                'sort_order' => 3,
            ],
            [
                'name' => 'Perlengkapan Dek Kapal',
                'slug' => 'perlengkapan-dek-kapal',
                'description' => 'Toko perlengkapan dek kapal terlengkap untuk kebutuhan operasional pelayaran. Tersedia tali tambat, jangkar, bollard, rantai jangkar, dan peralatan deck lainnya.',
                'meta_title' => 'Jual Perlengkapan Dek Kapal - Tali Tambat, Jangkar, Bollard',
                'meta_description' => 'Supplier perlengkapan dek kapal: tali tambat polypropylene, jangkar stockless, bollard, rantai jangkar, mooring rope, fender. Kualitas marine grade, harga pabrik.',
                'sort_order' => 4,
            ],
            [
                'name' => 'Sistem Kelistrikan Kapal',
                'slug' => 'sistem-kelistrikan-kapal',
                'description' => 'Distributor komponen kelistrikan dan elektronik kapal lengkap. Tersedia marine generator set, kabel marine XLPE, panel listrik, navigation light, dan perlengkapan elektrikal kapal.',
                'meta_title' => 'Jual Sistem Kelistrikan Kapal - Generator, Kabel Marine, Panel',
                'meta_description' => 'Toko komponen kelistrikan kapal: generator set marine, kabel XLPE marine, navigation light LED, panel distribusi, battery charger, alternator. Standar IEC 60092.',
                'sort_order' => 5,
            ],
            [
                'name' => 'Pompa & Valve',
                'slug' => 'pompa-dan-valve',
                'description' => 'Supplier pompa dan valve marine untuk sistem perpipaan kapal. Tersedia centrifugal pump, gear pump, butterfly valve, gate valve, ball valve untuk aplikasi air laut dan bahan bakar.',
                'meta_title' => 'Jual Pompa & Valve Marine - Centrifugal Pump, Butterfly Valve',
                'meta_description' => 'Distributor pompa dan valve marine: centrifugal pump, gear pump, submersible pump, butterfly valve, gate valve, ball valve bronze. Untuk sistem ballast, bilge, dan fuel oil.',
                'sort_order' => 6,
            ],
        ];

        foreach ($categories as $cat) {
            Category::create($cat);
        }

        $products = [
            // ===================== KATEGORI 1: Komponen Mesin Kapal =====================
            [
                'category_id' => 1, 'name' => 'Piston Ring Set Marine Diesel',
                'slug' => 'piston-ring-set-marine-diesel', 'sku' => 'MST-MK001',
                'description' => 'Piston ring set untuk mesin diesel kapal berbagai tipe. Material cast iron berkualitas tinggi dengan ketahanan aus yang sangat baik. Cocok untuk mesin Yanmar, Mitsubishi, Caterpillar, dan merek marine diesel lainnya.',
                'specifications' => "Material: Cast Iron Alloy\nDiameter: 150mm - 500mm\nTipe: Compression Ring / Oil Ring\nStandar: JIS B8031 / DIN 24911\nKekerasan: HRC 42-48",
                'price' => 2500000, 'stock' => 25,
                'meta_title' => 'Jual Piston Ring Set Mesin Diesel Kapal - Original Marine Grade',
                'meta_description' => 'Piston ring set marine diesel berkualitas. Cast iron alloy, diameter 150-500mm. Cocok untuk mesin Yanmar, Mitsubishi, Caterpillar. Tahan aus dan orisinal.',
                'alt_text' => 'Piston Ring Set Marine Diesel - Sparepart Mesin Kapal Original', 'is_featured' => true,
            ],
            [
                'category_id' => 1, 'name' => 'Cylinder Liner Marine Engine',
                'slug' => 'cylinder-liner-marine-engine', 'sku' => 'MST-MK002',
                'description' => 'Cylinder liner untuk mesin kapal dengan presisi tinggi. Material centrifugal cast iron dengan kekerasan seragam. Mereduksi gesekan dan memperpanjang umur mesin.',
                'specifications' => "Material: Centrifugal Cast Iron\nTipe: Wet / Dry Liner\nDiameter: 200mm - 600mm\nStandar: ISO 9001 / JIS\nKetebalan: 8mm - 25mm",
                'price' => 4750000, 'stock' => 15,
                'meta_title' => 'Cylinder Liner Mesin Kapal - Centrifugal Cast Iron Marine',
                'meta_description' => 'Cylinder liner marine engine centrifugal cast iron. Wet/dry liner diameter 200-600mm. Presisi tinggi, kekerasan seragam, memperpanjang umur mesin diesel kapal.',
                'alt_text' => 'Cylinder Liner Marine Engine - Komponen Mesin Kapal', 'is_featured' => true,
            ],
            [
                'category_id' => 1, 'name' => 'Turbocharger Assembly Marine',
                'slug' => 'turbocharger-assembly-marine', 'sku' => 'MST-MK003',
                'description' => 'Turbocharger assembly lengkap untuk mesin diesel kapal. Didesain untuk performa optimal di kondisi operasional berat. Material inconel alloy tahan panas tinggi.',
                'specifications' => "Tipe: Radial Flow / Axial Flow\nMaterial Turbine: Inconel Alloy\nBearing: Journal / Ball Bearing\nRasio Tekanan: 2.5 - 4.0 bar\nKapasitas Udara: 500 - 5000 kg/h",
                'price' => 18500000, 'stock' => 8,
                'meta_title' => 'Turbocharger Mesin Diesel Kapal - Radial & Axial Flow Marine',
                'meta_description' => 'Turbocharger assembly marine untuk mesin diesel kapal. Radial/axial flow, material inconel alloy tahan panas. Meningkatkan efisiensi bahan bakar hingga 20%.',
                'alt_text' => 'Turbocharger Assembly Marine - Sparepart Mesin Kapal', 'is_featured' => true,
            ],
            [
                'category_id' => 1, 'name' => 'Fuel Injection Pump Marine',
                'slug' => 'fuel-injection-pump-marine', 'sku' => 'MST-MK004',
                'description' => 'Pompa injeksi bahan bakar presisi tinggi untuk mesin diesel marine. Menjamin distribusi bahan bakar optimal ke setiap silinder untuk pembakaran sempurna.',
                'specifications' => "Tipe: Inline / Distributor Pump\nTekanan: 300 - 1200 bar\nJumlah Plunger: 4 - 8\nSertifikasi: Class Approved (NK/BKI/Lloyds)\nMaterial: Alloy Steel",
                'price' => 8900000, 'stock' => 12,
                'meta_title' => 'Fuel Injection Pump Mesin Diesel Marine - Pompa Injeksi Original',
                'meta_description' => 'Fuel injection pump marine tekanan 300-1200 bar. Tipe inline/distributor pump. Sertifikasi class approved. Menjamin injeksi bahan bakar presisi untuk mesin kapal.',
                'alt_text' => 'Fuel Injection Pump Marine - Pompa Injeksi Kapal', 'is_featured' => false,
            ],
            [
                'category_id' => 1, 'name' => 'Crankshaft Bearing Set Marine',
                'slug' => 'crankshaft-bearing-set-marine', 'sku' => 'MST-MK005',
                'description' => 'Set bearing crankshaft untuk mesin diesel kapal. Material bimetal/tri-metal dengan lapisan anti aus. Menopang putaran crankshaft dengan presisi tinggi.',
                'specifications' => "Material: Bi-metal / Tri-metal\nTipe: Main Bearing / Con Rod Bearing\nKetebalan: 1.5mm - 5mm\nStandar: DIN 1497 / JIS B801\nPelumasan: Oil Pressure Lubrication",
                'price' => 3200000, 'stock' => 20,
                'meta_title' => 'Crankshaft Bearing Set Marine - Main & Con Rod Bearing Kapal',
                'meta_description' => 'Crankshaft bearing set marine bimetal/tri-metal. Main bearing dan con rod bearing untuk mesin diesel kapal. Presisi tinggi, lapisan anti aus, standar DIN/JIS.',
                'alt_text' => 'Crankshaft Bearing Set Marine - Bearing Mesin Kapal',
            ],
            [
                'category_id' => 1, 'name' => 'Main Bearing Marine Diesel',
                'slug' => 'main-bearing-marine-diesel', 'sku' => 'MST-MK006',
                'description' => 'Main bearing untuk mesin diesel kapal berbagai ukuran. Material trimetal dengan overlay electroplating untuk ketahanan beban tinggi dan umur panjang.',
                'specifications' => "Material: Trimetal (Steel + Copper + Babbit)\nDiameter: 80mm - 400mm\nOverlay: Electroplating Tin\nStandar: SAE 783 / DIN 1705",
                'price' => 2800000, 'stock' => 18,
                'meta_title' => 'Main Bearing Mesin Diesel Kapal - Trimetal Marine Bearing',
                'meta_description' => 'Main bearing marine diesel trimetal dengan overlay electroplating. Diameter 80-400mm. Ketahanan beban tinggi untuk mesin kapal, umur panjang.',
                'alt_text' => 'Main Bearing Marine Diesel - Bearing Mesin Kapal Original',
            ],
            [
                'category_id' => 1, 'name' => 'Exhaust Valve Marine Diesel',
                'slug' => 'exhaust-valve-marine-diesel', 'sku' => 'MST-MK007',
                'description' => 'Exhaust valve untuk mesin diesel kapal tahan suhu tinggi. Material nimonic 80A dengan stellite facing untuk ketahanan korosi dan erosi gas buang.',
                'specifications' => "Material: Nimonic 80A / 21-4N\nStellite Facing: Yes\nDiameter Kepala: 40mm - 120mm\nSudut Seat: 30 / 45 derajat\nSuhu Operasi: Hingga 850\u00b0C",
                'price' => 1500000, 'stock' => 30,
                'meta_title' => 'Exhaust Valve Mesin Diesel Kapal - Nimonic 80A Stellite',
                'meta_description' => 'Exhaust valve marine diesel nimonic 80A dengan stellite facing. Tahan suhu tinggi hingga 850\u00b0C. Anti korosi dan erosi untuk mesin kapal.',
                'alt_text' => 'Exhaust Valve Marine Diesel - Katup Mesin Kapal',
            ],
            [
                'category_id' => 1, 'name' => 'Injection Nozzle Marine Diesel',
                'slug' => 'injection-nozzle-marine-diesel', 'sku' => 'MST-MK008',
                'description' => 'Injection nozzle untuk injector mesin diesel marine. Presisi tinggi dengan lubang micro drilling untuk atomisasi bahan bakar sempurna.',
                'specifications' => "Tipe: Multi-hole / Pintle\nJumlah Lubang: 4 - 10\nDiameter Lubang: 0.2mm - 0.5mm\nTekanan Buka: 200 - 350 bar\nMaterial: Bearing Steel",
                'price' => 650000, 'stock' => 50,
                'meta_title' => 'Injection Nozzle Marine Diesel - Nozzle Injector Kapal Original',
                'meta_description' => 'Injection nozzle marine diesel multi-hole/pintle. Micro drilling presisi untuk atomisasi sempurna. Meningkatkan efisiensi pembakaran mesin kapal.',
                'alt_text' => 'Injection Nozzle Marine Diesel - Nozzle Injector Kapal',
            ],

            // ===================== KATEGORI 2: Peralatan Navigasi =====================
            [
                'category_id' => 2, 'name' => 'Kompas Magnetik Marine SOLAS',
                'slug' => 'kompas-magnetik-marine-solas', 'sku' => 'MST-NV001',
                'description' => 'Kompas magnetik marine standar SOLAS untuk navigasi kapal. Dilengkapi dengan lampu penerangan internal, card kompas wet type untuk redaman getaran optimal.',
                'specifications' => "Tipe: Wet Card / Dry Card\nDiameter: 165mm / 185mm\nPenerangan: LED Internal 12V/24V\nStandar: SOLAS / IMO A.382(X)\nSertifikasi: MED / Wheelmark",
                'price' => 5600000, 'stock' => 10,
                'meta_title' => 'Kompas Magnetik Marine SOLAS - Navigasi Kapal Standar IMO',
                'meta_description' => 'Kompas magnetik marine SOLAS approved wet card. Diameter 165-185mm, lampu LED internal 12/24V. Standar IMO A.382(X), sertifikasi MED. Akurat dan tahan lama.',
                'alt_text' => 'Kompas Magnetik Marine SOLAS - Alat Navigasi Kapal', 'is_featured' => true,
            ],
            [
                'category_id' => 2, 'name' => 'GPS Marine Chartplotter 7 Inch',
                'slug' => 'gps-marine-chartplotter-7-inch', 'sku' => 'MST-NV002',
                'description' => 'GPS navigator marine dengan layar warna 7 inci dan chartplotter. Mendukung peta laut C-MAP, dual-frequency fishfinder, dan koneksi NMEA 2000.',
                'specifications' => "Layar: 7 inch TFT Color LCD\nAkurasi: < 3m (GPS)\nWaterproof: IPX7\nChart: C-MAP / Navionics\nNMEA: 2000 / 0183\nDaya: 12V DC",
                'price' => 12500000, 'stock' => 6,
                'meta_title' => 'GPS Marine Chartplotter 7 Inch - Navigator Kapal C-MAP',
                'meta_description' => 'GPS marine chartplotter 7 inch TFT color, C-MAP charts, dual-frequency fishfinder, NMEA 2000. Akurasi tinggi untuk navigasi kapal komersial dan rekreasi.',
                'alt_text' => 'GPS Marine Chartplotter 7 Inch - GPS Navigasi Kapal',
            ],
            [
                'category_id' => 2, 'name' => 'Radio VHF Marine DSC Class D',
                'slug' => 'radio-vhf-marine-dsc-class-d', 'sku' => 'MST-NV003',
                'description' => 'Radio VHF marine dengan DSC (Digital Selective Calling) Class D. Memenuhi standar GMDSS untuk komunikasi darurat dan rutin di laut.',
                'specifications' => "Frekuensi: 156 - 163 MHz\nDaya Output: 1W / 25W\nDSC: Class D (SC101)\nChannel: All international marine channels\nStandar: GMDSS / ITU-R M.493",
                'price' => 7800000, 'stock' => 9,
                'meta_title' => 'Radio VHF Marine DSC Class D - Komunikasi Kapal GMDSS',
                'meta_description' => 'Radio VHF marine DSC Class D standar GMDSS. Daya 1W/25W, semua channel internasional, fitur DSC untuk panggilan darurat. Komunikasi kapal yang andal.',
                'alt_text' => 'Radio VHF Marine DSC - Alat Komunikasi Kapal',
            ],
            [
                'category_id' => 2, 'name' => 'Echo Sounder Marine 600W',
                'slug' => 'echo-sounder-marine-600w', 'sku' => 'MST-NV004',
                'description' => 'Echo sounder / depth sounder marine 600W untuk pengukuran kedalaman air. Dual-frequency 50/200 kHz dengan layar monokrom atau warna.',
                'specifications' => "Daya: 600W RMS\nFrekuensi: 50 / 200 kHz\nKedalaman Maks: 1500m\nLayar: 5.6 inch LCD\nAlarm: Shallow / Deep Water Alarm\nDaya: 12 - 24V DC",
                'price' => 9800000, 'stock' => 7,
                'meta_title' => 'Echo Sounder Marine 600W - Depth Sounder Kapal 50/200 kHz',
                'meta_description' => 'Echo sounder marine 600W dual-frequency 50/200 kHz. Kedalaman maksimal 1500m, layar LCD 5.6 inch. Alat ukur kedalaman air untuk navigasi kapal.',
                'alt_text' => 'Echo Sounder Marine - Depth Sounder Kapal',
            ],
            [
                'category_id' => 2, 'name' => 'Radar Marine 4G Broadband 24 Inch',
                'slug' => 'radar-marine-4g-broadband-24-inch', 'sku' => 'MST-NV005',
                'description' => 'Radar marine 4G broadband dengan antena 24 inch. Teknologi FMCW untuk deteksi target jelas tanpa dead zone. Ideal untuk navigasi kapal komersial.',
                'specifications' => "Tipe: Broadband FMCW 4G\nAntena: 24 inch (60cm)\nRange: 0.1 - 72 NM\nDaya: 15W\nResolusi: High Definition\nMARPA: Auto Target Tracking",
                'price' => 45000000, 'stock' => 3,
                'meta_title' => 'Radar Marine 4G Broadband 24 Inch - FMCW Navigasi Kapal',
                'meta_description' => 'Radar marine 4G broadband FMCW 24 inch. Range 0.1-72 NM, high definition, MARPA auto target tracking. Deteksi target jelas tanpa dead zone.',
                'alt_text' => 'Radar Marine 4G Broadband - Radar Navigasi Kapal', 'is_featured' => true,
            ],
            [
                'category_id' => 2, 'name' => 'AIS Transponder Class B Marine',
                'slug' => 'ais-transponder-class-b-marine', 'sku' => 'MST-NV006',
                'description' => 'AIS (Automatic Identification System) transponder Class B untuk kapal. Memancarkan dan menerima data identifikasi kapal, posisi, kecepatan, dan haluan.',
                'specifications' => "Tipe: Class B\nFrekuensi: 161.975 / 162.025 MHz\nDaya: 2W\nGPS: Internal / External\nInterface: NMEA 0183 / 2000\nStandar: ITU-R M.1371",
                'price' => 18500000, 'stock' => 5,
                'meta_title' => 'AIS Transponder Class B Marine - Automatic Identification System',
                'meta_description' => 'AIS transponder Class B marine untuk identifikasi kapal. Memancarkan posisi, kecepatan, haluan. Interface NMEA 0183/2000. Wajib untuk keselamatan pelayaran.',
                'alt_text' => 'AIS Transponder Class B - Alat Navigasi Kapal',
            ],

            // ===================== KATEGORI 3: Peralatan Keselamatan =====================
            [
                'category_id' => 3, 'name' => 'Life Jacket SOLAS Approved 150N',
                'slug' => 'life-jacket-solas-approved-150n', 'sku' => 'MST-KS001',
                'description' => 'Life jacket standar SOLAS dengan daya apung 150N. Dilengkapi lampu otomatis, peluit, reflective tape, dan crotch strap. Nyaman dipakai dengan kerah kepala.',
                'specifications' => "Daya Apung: 150N (adult)\nMaterial: Nylon / PVC\nSertifikasi: SOLAS / MED / EC\nLampu: Automatic LED\nBerat: < 1.5 kg\nWarna: Orange / Yellow",
                'price' => 450000, 'stock' => 100,
                'meta_title' => 'Life Jacket SOLAS 150N - Jaket Pelampung Kapal Approved',
                'meta_description' => 'Life jacket SOLAS approved 150N dengan lampu otomatis LED, peluit, reflective tape. Sertifikasi MED/EC, nyaman dipakai. Wajib untuk keselamatan kapal.',
                'alt_text' => 'Life Jacket SOLAS 150N - Jaket Pelampung Kapal', 'is_featured' => true,
            ],
            [
                'category_id' => 3, 'name' => 'Life Raft SOLAS A Pack 25 Person',
                'slug' => 'life-raft-solas-a-pack-25-person', 'sku' => 'MST-KS002',
                'description' => 'Life raft inflatable kapasitas 25 orang dengan SOLAS A Pack lengkap. Terdiri dari canopy, lampu, survival pack, dan peralatan darurat sesuai standar SOLAS.',
                'specifications' => "Kapasitas: 25 orang\nPack: SOLAS A Pack (Full)\nServis: Annual / 5 Year Overhaul\nKanopi: Double Layer Orange\nSertifikasi: SOLAS / MED / Wheelmark\nBerat: ~180 kg",
                'price' => 65000000, 'stock' => 4,
                'meta_title' => 'Life Raft SOLAS A Pack 25 Person - Rakit Penyelamat Kapal',
                'meta_description' => 'Life raft SOLAS A Pack kapasitas 25 orang. Dilengkapi survival pack lengkap, canopy double layer. Sertifikasi MED/Wheelmark. Servis tahunan terjadwal.',
                'alt_text' => 'Life Raft SOLAS A Pack - Rakit Penyelamat Kapal 25 Orang',
            ],
            [
                'category_id' => 3, 'name' => 'Fire Extinguisher CO2 5 Kg Marine',
                'slug' => 'fire-extinguisher-co2-5kg-marine', 'sku' => 'MST-KS003',
                'description' => 'Tabung pemadam api CO2 5kg untuk kapal. Efektif untuk kebakaran kelas B dan C. Dilengkapi safety pin, pressure gauge, dan sertifikasi marine.',
                'specifications' => "Isi: 5 kg CO2\nKelas Kebakaran: B, C\nTekanan: 56 bar (20\u00b0C)\nTabung: Steel / Alloy\nSertifikasi: SOLAS / MED / BKI\nValve: Brass Forged",
                'price' => 1800000, 'stock' => 30,
                'meta_title' => 'Fire Extinguisher CO2 5 Kg Marine - Alat Pemadam Kapal SOLAS',
                'meta_description' => 'Fire extinguisher CO2 5kg marine SOLAS approved. Kelas B dan C, tekanan 56 bar. Safety pin dan pressure gauge. Sertifikasi MED/BKI untuk kapal.',
                'alt_text' => 'Fire Extinguisher CO2 5Kg - Alat Pemadam Kebakaran Kapal',
            ],
            [
                'category_id' => 3, 'name' => 'EPIRB 406MHz dengan GPS Built-in',
                'slug' => 'epirb-406mhz-dengan-gps-built-in', 'sku' => 'MST-KS004',
                'description' => 'EPIRB (Emergency Position Indicating Radio Beacon) 406MHz dengan GPS built-in. Mengirimkan sinyal darurat ke satelit Cospas-Sarsat dengan posisi akurat.',
                'specifications' => "Frekuensi: 406.025 MHz + 121.5 MHz\nGPS: Built-in 66-channel\nBaterai: Lithium, 48 jam (minimum)\nKandungan: Free-drifting / Category I\nStandar: IMO / COSPAS-SARSAT\nSertifikasi: MED / BKI",
                'price' => 15000000, 'stock' => 7,
                'meta_title' => 'EPIRB 406MHz GPS Built-in - Beacon Darurat Kapal SOLAS',
                'meta_description' => 'EPIRB 406MHz dengan GPS built-in 66-channel. Mengirim sinyal darurat ke satelit Cospas-Sarsat. Baterai 48 jam. Wajib untuk kapal SOLAS.',
                'alt_text' => 'EPIRB 406MHz GPS - Beacon Darurat Kapal', 'is_featured' => true,
            ],
            [
                'category_id' => 3, 'name' => 'Immersion Suit SOLAS Approved',
                'slug' => 'immersion-suit-solas-approved', 'sku' => 'MST-KS005',
                'description' => 'Immersion suit / survival suit SOLAS approved untuk perlindungan hipotermia di air dingin. Bahan neoprene dengan seal ketat di pergelangan tangan dan leher.',
                'specifications' => "Material: Neoprene 5mm\nWaterproof: Yes (leak tested)\nThermal Protection: SOLAS compliant\nSertifikasi: MED / EC\nWarna: Orange / Red\nReflective Tape: SOLAS spec",
                'price' => 3200000, 'stock' => 15,
                'meta_title' => 'Immersion Suit SOLAS Approved - Survival Suit Kapal Neoprene',
                'meta_description' => 'Immersion suit SOLAS approved neoprene 5mm. Perlindungan hipotermia, waterproof, reflective tape. Sertifikasi MED/EC. Wajib untuk kapal niaga.',
                'alt_text' => 'Immersion Suit SOLAS - Survival Suit Keselamatan Kapal',
            ],
            [
                'category_id' => 3, 'name' => 'SART Radar Transponder Marine',
                'slug' => 'sart-radar-transponder-marine', 'sku' => 'MST-KS006',
                'description' => 'SART (Search and Rescue Radar Transponder) untuk kapal. Menghasilkan sinyal 12 blips pada layar radar kapal penyelamat dalam radius minimal 8 NM.',
                'specifications' => "Frekuensi: 9.2 - 9.5 GHz (X-band)\nDeteksi: < 5 NM (minimal 8 NM)\nBaterai: 96 jam standby / 8 jam active\nStandar: IMO / SOLAS\nSertifikasi: MED Wheelmark",
                'price' => 18500000, 'stock' => 5,
                'meta_title' => 'SART Radar Transponder Marine - Search and Rescue SOLAS',
                'meta_description' => 'SART radar transponder marine X-band. Deteksi minimal 8 NM, baterai 96 jam standby. Alat pencarian dan penyelamatan kapal standar SOLAS.',
                'alt_text' => 'SART Radar Transponder - Alat Penyelamat Kapal',
            ],

            // ===================== KATEGORI 4: Perlengkapan Dek Kapal =====================
            [
                'category_id' => 4, 'name' => 'Tali Tambat Polypropylene 40mm',
                'slug' => 'tali-tambat-polypropylene-40mm', 'sku' => 'MST-DK001',
                'description' => 'Tali tambat kapal polypropylene 40mm, ringan dan tahan terhadap air laut serta sinar UV. Tersedia dalam panjang 200 meter per coil.',
                'specifications' => "Diameter: 40mm\nMaterial: 100% Polypropylene\nBreaking Strength: 12 ton\nPanjang: 200m / coil\nTipe: 3-strand / 8-strand\nWarna: Putih / Biru",
                'price' => 3500000, 'stock' => 20,
                'meta_title' => 'Tali Tambat Polypropylene 40mm - Mooring Rope Kapal Marine',
                'meta_description' => 'Tali tambat kapal polypropylene 40mm, breaking strength 12 ton. Ringan, tahan UV dan air laut. Panjang 200m per coil. 3-strand/8-strand.',
                'alt_text' => 'Tali Tambat Polypropylene 40mm - Tali Kapal Marine',
            ],
            [
                'category_id' => 4, 'name' => 'Stockless Anchor 500 Kg Cast Steel',
                'slug' => 'stockless-anchor-500-kg-cast-steel', 'sku' => 'MST-DK002',
                'description' => 'Jangkar stockless 500kg dari cast steel berkualitas. Didesain untuk kapal niaga dan tongkang. Class approved dengan sertifikasi material lengkap.',
                'specifications' => "Berat: 500 kg\nTipe: Stockless (Hall / AC-14)\nMaterial: Cast Steel (ASTM A27)\nSWL: 3 x berat\nSertifikasi: BKI / NK / Lloyds\nFinishing: Galvanized / Cat Epoxy",
                'price' => 22000000, 'stock' => 3,
                'meta_title' => 'Stockless Anchor 500 Kg - Jangkar Kapal Cast Steel Class Approved',
                'meta_description' => 'Stockless anchor 500 kg cast steel ASTM A27. Tipe Hall/AC-14. Sertifikasi BKI/NK/Lloyds. Finishing galvanized/epoxy. Untuk kapal niaga dan tongkang.',
                'alt_text' => 'Stockless Anchor 500 Kg - Jangkar Kapal Cast Steel',
            ],
            [
                'category_id' => 4, 'name' => 'Bollard Cast Iron 10 Ton SWL',
                'slug' => 'bollard-cast-iron-10-ton-swl', 'sku' => 'MST-DK003',
                'description' => 'Bollard besi cor 10 ton untuk tambat kapal di dermaga. Hot-dip galvanized anti korosi. Desain double bitt untuk pengikatan tali yang aman.',
                'specifications' => "Kapasitas: 10 ton SWL\nMaterial: Cast Iron G25 / Ductile Iron\nFinishing: Hot-dip Galvanized\nTipe: Double Bitt\nBaut: JIS / Metric\nStandar: ISO 3913",
                'price' => 8500000, 'stock' => 10,
                'meta_title' => 'Bollard Cast Iron 10 Ton - Bitt Tambat Kapal Hot-dip Galvanized',
                'meta_description' => 'Bollard cast iron 10 ton SWL hot-dip galvanized. Double bitt desain, anti korosi. Standar ISO 3913 untuk tambat kapal di dermaga.',
                'alt_text' => 'Bollard Cast Iron 10 Ton - Bitt Tambat Kapal',
            ],
            [
                'category_id' => 4, 'name' => 'Rantai Jangkar Grade 2 32mm',
                'slug' => 'rantai-jangkar-grade-2-32mm', 'sku' => 'MST-DK004',
                'description' => 'Rantai jangkar kapal grade 2 diameter 32mm. Material baja karbon tinggi dengan heat treatment. Dilengkapi dengan kenter shackle setiap 27.5 meter.',
                'specifications' => "Diameter: 32mm\nGrade: 2 (Grade U2)\nMaterial: Carbon Steel\nPanjang: 27.5m / length\nStandar: ISO 1704 / BKI\nSertifikasi: Class Approved",
                'price' => 38000000, 'stock' => 2,
                'meta_title' => 'Rantai Jangkar Grade 2 32mm - Anchor Chain Kapal ISO 1704',
                'meta_description' => 'Rantai jangkar kapal grade 2 diameter 32mm. Material carbon steel heat treated. Dilengkapi kenter shackle. Sertifikasi class approved, standar ISO 1704.',
                'alt_text' => 'Rantai Jangkar Grade 2 32mm - Rantai Kapal',
            ],
            [
                'category_id' => 4, 'name' => 'Marine Fender Rubber Cylinder 500mm',
                'slug' => 'marine-fender-rubber-cylinder-500mm', 'sku' => 'MST-DK005',
                'description' => 'Fender karet kapal tipe cylindrical diameter 500mm. Menyerap energi benturan saat sandar. Material karet alam berkualitas tinggi tahan abrasi.',
                'specifications' => "Tipe: Cylindrical\nDiameter: 500mm x 1000mm\nReaction Force: 80 kN\nEnergy Absorption: 120 kNm\nTire Pressure: 0.05 - 0.08 MPa\nMaterial: Natural Rubber / SBR",
                'price' => 12000000, 'stock' => 6,
                'meta_title' => 'Marine Fender Rubber Cylinder 500mm - Fender Karet Kapal',
                'meta_description' => 'Marine fender karet cylindrical 500mm x 1000mm. Menyerap energi benturan saat sandar. Reaksi 80 kN, absorpsi 120 kNm. Material karet alam tahan abrasi.',
                'alt_text' => 'Marine Fender Rubber Cylinder - Fender Karet Kapal', 'is_featured' => true,
            ],
            [
                'category_id' => 4, 'name' => 'Mooring Rope Nylon 32mm',
                'slug' => 'mooring-rope-nylon-32mm', 'sku' => 'MST-DK006',
                'description' => 'Tali mooring nylon 32mm dengan elastisitas tinggi untuk tambat kapal. Tahan abrasi dan beban kejut. Ideal untuk mooring lines kapal niaga.',
                'specifications' => "Diameter: 32mm\nMaterial: Nylon 66 / Polyamide\nBreaking Strength: 18 ton\nElongation: 30 - 40%\nPanjang: 220m / coil\nTipe: 8-strand plaited",
                'price' => 6800000, 'stock' => 12,
                'meta_title' => 'Mooring Rope Nylon 32mm - Tali Tambat Kapal Elastis Tinggi',
                'meta_description' => 'Mooring rope nylon 32mm breaking strength 18 ton. Elastisitas 30-40%, tahan abrasi dan beban kejut. Ideal untuk mooring lines kapal niaga.',
                'alt_text' => 'Mooring Rope Nylon 32mm - Tali Tambat Kapal',
            ],

            // ===================== KATEGORI 5: Sistem Kelistrikan Kapal =====================
            [
                'category_id' => 5, 'name' => 'Marine Generator Set 50 kVA Diesel',
                'slug' => 'marine-generator-set-50-kva-diesel', 'sku' => 'MST-EL001',
                'description' => 'Generator set marine 50 kVA diesel dengan pendingin air laut. AVR otomatis untuk output tegangan stabil. Panel kontrol lengkap dengan safety system.',
                'specifications' => "Daya: 50 kVA / 40 kW\nVoltage: 380/220V 3 Phase\nFrekuensi: 50 Hz\nMesin: Diesel 4 cylinder\nPendingin: Freshwater / Seawater\nAVR: Automatic Voltage Regulator",
                'price' => 125000000, 'stock' => 2,
                'meta_title' => 'Marine Generator Set 50 kVA Diesel - Genset Kapal 380V',
                'meta_description' => 'Marine generator set 50 kVA diesel pendingin air laut. AVR otomatis, panel kontrol safety system. Output 380/220V 3 phase. Untuk kapal niaga dan kerja.',
                'alt_text' => 'Marine Generator Set 50 kVA - Genset Kapal Diesel', 'is_featured' => true,
            ],
            [
                'category_id' => 5, 'name' => 'Kabel Marine XLPE 35mm2 LSZH',
                'slug' => 'kabel-marine-xlpe-35mm2-lszh', 'sku' => 'MST-EL002',
                'description' => 'Kabel marine XLPE 35mm2 tahan api, minyak, dan air laut. Sheath LSZH (Low Smoke Zero Halogen) untuk keamanan maksimal di area tertutup.',
                'specifications' => "Penampang: 35 mm2\nInsulasi: XLPE (Cross-linked Polyethylene)\nSheath: LSZH (Low Smoke Zero Halogen)\nTegangan: 0.6/1 kV\nStandar: IEC 60092 / IEEE 1580\nWarna: Hitam / Biru",
                'price' => 85000, 'stock' => 500,
                'meta_title' => 'Kabel Marine XLPE 35mm2 LSZH - Kabel Kapal IEC 60092',
                'meta_description' => 'Kabel marine XLPE 35mm2 LSZH tahan api dan minyak. Tegangan 0.6/1 kV, sheath low smoke zero halogen. Standar IEC 60092 untuk instalasi listrik kapal.',
                'alt_text' => 'Kabel Marine XLPE 35mm2 - Kabel Listrik Kapal',
            ],
            [
                'category_id' => 5, 'name' => 'Navigation Light Set LED COLREG',
                'slug' => 'navigation-light-set-led-colreg', 'sku' => 'MST-EL003',
                'description' => 'Set lampu navigasi LED lengkap untuk kapal. Memenuhi standar COLREG 72 untuk visibilitas siang dan malam. Tahan air dan korosi.',
                'specifications' => "Tipe: LED Marine\nVisibilitas: 2 - 3 NM\nStandar: COLREG 72 / IMO\nWarna: Merah, Hijau, Putih, Kuning\nWaterproof: IP56\nTegangan: 12V / 24V DC",
                'price' => 6500000, 'stock' => 12,
                'meta_title' => 'Navigation Light Set LED - Lampu Navigasi Kapal COLREG 72',
                'meta_description' => 'Navigation light set LED marine standar COLREG 72. Visibilitas 2-3 NM, waterproof IP56. Lampu merah, hijau, putih, kuning untuk keselamatan pelayaran malam.',
                'alt_text' => 'Navigation Light Set LED - Lampu Navigasi Kapal',
            ],
            [
                'category_id' => 5, 'name' => 'Marine Battery Charger 24V 30A',
                'slug' => 'marine-battery-charger-24v-30a', 'sku' => 'MST-EL004',
                'description' => 'Battery charger marine 24V 30A dengan 3-stage charging (bulk, absorption, float). Dilengkapi proteksi overcurrent, short circuit, dan reverse polarity.',
                'specifications' => "Input: 220V AC 50Hz\nOutput: 24V DC 30A\nCharging Mode: 3-Stage (Bulk/Absorption/Float)\nProteksi: Overcurrent, Short, Reverse Polarity\nMaterial: Aluminium casing\nStandar: Marine Grade",
                'price' => 5200000, 'stock' => 8,
                'meta_title' => 'Marine Battery Charger 24V 30A - Charger Aki Kapal 3-Stage',
                'meta_description' => 'Marine battery charger 24V 30A 3-stage charging (bulk/absorption/float). Proteksi overcurrent, short circuit, reverse polarity. Untuk aki kapal.',
                'alt_text' => 'Marine Battery Charger 24V - Charger Aki Kapal',
            ],
            [
                'category_id' => 5, 'name' => 'Main Switchboard Panel Marine 500A',
                'slug' => 'main-switchboard-panel-marine-500a', 'sku' => 'MST-EL005',
                'description' => 'Main switchboard panel marine 500A untuk distribusi listrik kapal. Dilengkapi ACB, MCCB, meters, dan busbar tembaga. Desain custom sesuai kebutuhan.',
                'specifications' => "Kapasitas: 500A 3 Phase\nTegangan: 380/220V AC\nKomponen: ACB / MCCB / Metering\nBusbar: Tembaga (Copper)\nStandar: IEC 61439 / BKI\nProtection: IP22 / IP44",
                'price' => 85000000, 'stock' => 2,
                'meta_title' => 'Main Switchboard Panel Marine 500A - Panel Distribusi Kapal',
                'meta_description' => 'Main switchboard panel marine 500A 3 phase. ACB, MCCB, metering lengkap. Busbar tembaga, standar IEC 61439. Custom desain untuk distribusi listrik kapal.',
                'alt_text' => 'Main Switchboard Panel Marine - Panel Listrik Kapal',
            ],
            [
                'category_id' => 5, 'name' => 'Marine Alternator 24V 80A',
                'slug' => 'marine-alternator-24v-80a', 'sku' => 'MST-EL006',
                'description' => 'Alternator marine 24V 80A untuk pengisian aki kapal. Tahan air dan korosi dengan double bearing. Regulator internal voltage stabil.',
                'specifications' => "Output: 24V 80A\nMax RPM: 6000 RPM\nRegulator: Internal IC\nBearing: Double Ball Bearing\nProteksi: Splash Proof / Corrosion Resistant\nType: Marine Grade",
                'price' => 3800000, 'stock' => 10,
                'meta_title' => 'Marine Alternator 24V 80A - Alternator Kapal Double Bearing',
                'meta_description' => 'Marine alternator 24V 80A tahan air dan korosi. Double ball bearing, regulator internal IC. Pengisian aki kapal stabil dan andal.',
                'alt_text' => 'Marine Alternator 24V 80A - Alternator Pengisian Aki Kapal',
            ],

            // ===================== KATEGORI 6: Pompa & Valve =====================
            [
                'category_id' => 6, 'name' => 'Centrifugal Pump Marine 100m3/h',
                'slug' => 'centrifugal-pump-marine-100m3h', 'sku' => 'MST-PV001',
                'description' => 'Pompa sentrifugal marine 100m3/h untuk aplikasi pendingin, ballast, dan bilge. Casing besi cor / bronze dengan impeller bronze tahan korosi.',
                'specifications' => "Kapasitas: 100 m3/h\nTotal Head: 30m\nMaterial Casing: Cast Iron / Bronze\nImpeller: Bronze / SS316\nSeal: Mechanical Seal (Carbon/Ceramic)\nFlange: JIS 10K / DIN PN16",
                'price' => 35000000, 'stock' => 5,
                'meta_title' => 'Centrifugal Pump Marine 100m3/h - Pompa Ballast & Bilge Kapal',
                'meta_description' => 'Centrifugal pump marine 100m3/h head 30m. Casing besi cor/bronze, impeller bronze/SS316, mechanical seal. Untuk ballast, bilge, dan cooling kapal.',
                'alt_text' => 'Centrifugal Pump Marine - Pompa Sentrifugal Kapal',
            ],
            [
                'category_id' => 6, 'name' => 'Butterfly Valve Marine DN150 Bronze',
                'slug' => 'butterfly-valve-marine-dn150-bronze', 'sku' => 'MST-PV002',
                'description' => 'Butterfly valve DN150 (6 inch) bronze untuk sistem perpipaan air laut. Disc stainless steel 316 dengan seat EPDM tahan air laut.',
                'specifications' => "Ukuran: DN150 (6 inch)\nMaterial Body: Bronze / Alu Bronze\nDisc: SS316 / CF8M\nSeat: EPDM / PTFE\nOperasi: Handle / Gearbox\nFlange: JIS 10K / ANSI 150",
                'price' => 4800000, 'stock' => 18,
                'meta_title' => 'Butterfly Valve Marine DN150 Bronze - Valve Air Laut Kapal',
                'meta_description' => 'Butterfly valve marine DN150 bronze, disc SS316, seat EPDM. Handle/gearbox operasi. Untuk sistem air laut, ballast, dan cooling kapal.',
                'alt_text' => 'Butterfly Valve Marine DN150 - Valve Pipa Kapal',
            ],
            [
                'category_id' => 6, 'name' => 'Gear Pump Fuel Oil Transfer 5m3/h',
                'slug' => 'gear-pump-fuel-oil-transfer-5m3h', 'sku' => 'MST-PV003',
                'description' => 'Gear pump untuk transfer bahan bakar (fuel oil / diesel) kapal. Self-priming dengan relief valve internal. Material cast iron dengan gear hardened steel.',
                'specifications' => "Kapasitas: 5 m3/h\nTekanan: 7 bar\nMaterial: Cast Iron / Bronze\nGear: Hardened Steel / Bronze\nViskositas: Hingga 500 cSt\nSelf-Priming: Yes (dry run < 30s)",
                'price' => 12000000, 'stock' => 8,
                'meta_title' => 'Gear Pump Fuel Oil Transfer 5m3/h - Pompa Transfer BBM Kapal',
                'meta_description' => 'Gear pump fuel oil transfer 5m3/h self-priming. Tekanan 7 bar, relief valve internal. Untuk transfer solar/bahan bakar kapal. Material cast iron tahan lama.',
                'alt_text' => 'Gear Pump Fuel Oil Transfer - Pompa Transfer BBM Kapal',
            ],
            [
                'category_id' => 6, 'name' => 'Gate Valve Marine DN200 Cast Steel',
                'slug' => 'gate-valve-marine-dn200-cast-steel', 'sku' => 'MST-PV004',
                'description' => 'Gate valve DN200 (8 inch) cast steel untuk sistem pipa kapal. Wedge gate solid, seat ring SS13, bonnet bolted. Operasi handwheel.',
                'specifications' => "Ukuran: DN200 (8 inch)\nMaterial Body: Cast Steel WCB\nTrim: SS13 / 13Cr\nWedge: Solid Wedge / Flexible Wedge\nBonnet: Bolted / Pressure Seal\nStandar: API 600 / JIS B2071",
                'price' => 15000000, 'stock' => 6,
                'meta_title' => 'Gate Valve Marine DN200 Cast Steel - Katup Gerbang Kapal',
                'meta_description' => 'Gate valve marine DN200 cast steel WCB. Wedge solid, seat SS13, bonnet bolted. Operasi handwheel. Standar API 600 untuk sistem perpipaan kapal.',
                'alt_text' => 'Gate Valve Marine DN200 - Katup Gerbang Kapal Cast Steel',
            ],
            [
                'category_id' => 6, 'name' => 'Ball Valve Marine 2 Inch Bronze',
                'slug' => 'ball-valve-marine-2-inch-bronze', 'sku' => 'MST-PV005',
                'description' => 'Ball valve 2 inch bronze untuk aplikasi marine. Full bore dengan ball chrome plated brass / SS316. Handle lockable untuk keamanan.',
                'specifications' => "Ukuran: 2 inch (50mm)\nMaterial Body: Bronze / Alu Bronze\nBall: Chrome Plated Brass / SS316\nSeat: PTFE / Teflon\nOperasi: Lever Handle (Lockable)\nStandar: JIS F7300 / ANSI",
                'price' => 1800000, 'stock' => 25,
                'meta_title' => 'Ball Valve Marine 2 Inch Bronze - Katup Bola Kapal Full Bore',
                'meta_description' => 'Ball valve marine 2 inch bronze full bore. Ball chrome plated brass/SS316, seat PTFE. Handle lockable. Standar JIS F7300 untuk pipa kapal.',
                'alt_text' => 'Ball Valve Marine 2 Inch - Katup Bola Kapal Bronze',
            ],
            [
                'category_id' => 6, 'name' => 'Submersible Pump Marine 50m3/h',
                'slug' => 'submersible-pump-marine-50m3h', 'sku' => 'MST-PV006',
                'description' => 'Pompa submersible marine 50m3/h untuk bilge dan drainage. Motor submersible tahan air, impeller corrosion resistant. Auto-start dengan float switch.',
                'specifications' => "Kapasitas: 50 m3/h\nHead: 15m\nMotor: 3 HP 380V / 220V\nMaterial: SS304 / Cast Iron\nStart: Auto (Float Switch)\nProteksi: Thermal Overload",
                'price' => 28000000, 'stock' => 4,
                'meta_title' => 'Submersible Pump Marine 50m3/h - Pompa Bilge Kapal Otomatis',
                'meta_description' => 'Submersible pump marine 50m3/h untuk bilge dan drainage. Motor 3 HP submersible, auto-start float switch. Proteksi thermal overload, material SS304.',
                'alt_text' => 'Submersible Pump Marine - Pompa Bilge Kapal', 'is_featured' => true,
            ],
        ];

        foreach ($products as $prod) {
            Product::create($prod);
        }

        echo "Seeding completed!\n";
        echo "Admin: admin@mitrast.com / admin123\n";
        echo "Categories: 6\n";
        echo "Products: " . count($products) . "\n";

        $this->call(StockMovementSeeder::class);
    }
}
